Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -53,19 +53,17 @@ steps:
 
 - script: |
     echo "🔍 Ejecutando Snyk Test..."
-    DEBUG=*snyk* ./snyk  test --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f    code test --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f  || echo "⚠️ Error en Snyk Test"
+    DEBUG=*snyk* ./snyk  test     code test --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f  || echo "⚠️ Error en Snyk Test"
   displayName: '🔍 Ejecutar Snyk Test'
-  env:
-    SNYK_TOKEN: $(SNYK_TOKEN) 
+
 
 
 # 7️⃣ Enviar resultados a Snyk Web
 - script: |
     echo "📡 Enviando datos a Snyk Web..."
-     DEBUG=*snyk*  ./snyk monitor --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f    --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f || echo "⚠️ Error al enviar datos a Snyk Web"
+     DEBUG=*snyk*  ./snyk monitor    --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f || echo "⚠️ Error al enviar datos a Snyk Web"
   displayName: '📡 Enviar datos a Snyk Web'
-  env:
-    SNYK_TOKEN: $(SNYK_TOKEN) 
+ 
 
 # 8️⃣ Publicar reportes de Snyk en Azure DevOps
 - task: PublishPipelineArtifact@1
