Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -14,6 +14,9 @@ steps:
     pip install --no-cache-dir --index-url https://pypi.org/simple  -r requirements.txt  # Instala dependencias
   displayName: 'Instalar dependencias'
 
+- script: chmod +x $(Build.SourcesDirectory) -R
+  displayName: 'Dar permisos a los archivos'
+
 # 1️⃣ Verifica el entorno del pipeline
 - script: |
     echo "📂 Directorio actual:"
@@ -50,7 +53,7 @@ steps:
 
 - script: |
     echo "🔍 Ejecutando Snyk Test..."
-    DEBUG=*snyk* ./snyk  --project-name="$(Build.Repository.Name)"  code test --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f  || echo "⚠️ Error en Snyk Test"
+    DEBUG=*snyk* ./snyk --org="cody-FYykEUMvqvyLd95NeaEsjZ"  --project-name="$(Build.Repository.Name)"  code test --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f  || echo "⚠️ Error en Snyk Test"
   displayName: '🔍 Ejecutar Snyk Test'
   env:
     SNYK_TOKEN: $(SNYK_TOKEN) 
@@ -59,7 +62,7 @@ steps:
 # 7️⃣ Enviar resultados a Snyk Web
 - script: |
     echo "📡 Enviando datos a Snyk Web..."
-     DEBUG=*snyk*  ./snyk monitor --project-name="$(Build.Repository.Name)"  --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f || echo "⚠️ Error al enviar datos a Snyk Web"
+     DEBUG=*snyk*  ./snyk monitor --org="cody-FYykEUMvqvyLd95NeaEsjZ"  --project-name="$(Build.Repository.Name)"  --command=python3 --file=requirements.txt --package-manager=pip  --debug  --org=4c1ee31d-3158-4a30-ae75-b754fa29b29f || echo "⚠️ Error al enviar datos a Snyk Web"
   displayName: '📡 Enviar datos a Snyk Web'
   env:
     SNYK_TOKEN: $(SNYK_TOKEN) 
