Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,17 +2,14 @@ trigger:
 - main  # O el branch donde quieres ejecutarlo
 
 pool:
-  vmImage: 'ubuntu-latest'
+  vmImage: 'Agent'
 
 variables:
   - group: varcody    # Contiene la variable SNYK_TOKEN
 
 steps:
 - checkout: self 
-- script: |
-    pip install --no-cache-dir --index-url https://pypi.org/simple --upgrade pip  # Actualiza pip
-    pip install --no-cache-dir --index-url https://pypi.org/simple  -r requirements.txt  # Instala dependencias
-  displayName: 'Instalar dependencias'
+
 
 - script: chmod +x $(Build.SourcesDirectory) -R
   displayName: 'Dar permisos a los archivos'
@@ -31,20 +28,13 @@ steps:
 
 
 
-- script: |
-    echo "📦 Descargando la última versión de Snyk CLI..."
-    curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
-    chmod +x snyk
-    ./snyk --version
-    ./snyk --help
-  displayName: '📦 Descargar y verificar Snyk CLI'
 
 
 
 # 3️⃣ Autenticar con Snyk Web
 - script: |
     echo "🔑 Autenticando Snyk..."
-    ./snyk auth $(SNYK_TOKEN)
+    snyk auth $(SNYK_TOKEN)
   displayName: '🔑 Autenticación en Snyk'
 
 # 4️⃣ Ejecutar análisis de seguridad en código fuente
@@ -53,7 +43,7 @@ steps:
 
 - script: |
     echo "🔍 Ejecutando Snyk Test..."
-    DEBUG=*snyk* ./snyk  code test  --org=8e65c7c0-621c-4f92-8923-5fd7aa2bbd4d || echo "⚠️ Error en Snyk Test"
+    DEBUG=*snyk* ./snyk  code test  --project-name="$(Build.Repository.Name)"|| echo "⚠️ Error en Snyk Test"
   displayName: '🔍 Ejecutar Snyk Test'
 
 
@@ -61,7 +51,7 @@ steps:
 # 7️⃣ Enviar resultados a Snyk Web
 - script: |
     echo "📡 Enviando datos a Snyk Web..."
-     DEBUG=*snyk*  ./snyk monitor   --org=8e65c7c0-621c-4f92-8923-5fd7aa2bbd4d || echo "⚠️ Error al enviar datos a Snyk Web"
+    snyk monitor --project-name="$(Build.Repository.Name)"  - || echo "⚠️ Error al enviar datos a Snyk Web"
   displayName: '📡 Enviar datos a Snyk Web'
  
 
