Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,9 +22,17 @@ steps:
     ls -lhR $(Build.SourcesDirectory)
   displayName: '📂 Verificar entorno antes de Snyk'
 
+
+# 1️⃣ Verifica el entorno del pipeline
+- script: |
+    echo "📂 Pip freeze:"
+     pip freeze > requirements.txt
+    echo "📂 Validacion:"
+    pip check
+  displayName: '📂 Validaciones requirements - validaciones '
+
+
 # 2️⃣ Instalar Snyk CLI si no está disponible
-
-
 
 
 
@@ -42,7 +50,7 @@ steps:
 - script: |
     echo "🔍 Ejecutando Snyk Test..."
     snyk auth $(SNYK_TOKEN)
-    snyk   test  --file=requirements.txt   --project-name="$(Build.Repository.Name)"|| echo "⚠️ Error en Snyk Test"
+    snyk   test    --project-name="$(Build.Repository.Name)"|| echo "⚠️ Error en Snyk Test"
     snyk monitor --project-name="$(Build.Repository.Name)"  - || echo "⚠️ Error al enviar datos a Snyk Web"
   displayName: '🔍 Ejecutar Snyk Test'
 
